import { useState, useCallback, useMemo } from 'react'
import { HybridSheet } from '~/components/HybridSheet'
import { FullSheet } from '~/components/FullSheet'
import { LogPane } from '~/components/LogPane'
import type { LogEntry } from '~/components/LogPane'
import { createClient } from '~/lib/llm'
import type Anthropic from '@anthropic-ai/sdk'

const HYBRID_EXPLANATION = `The building has a front door, but nothing behind it. This spreadsheet UI is coded in React — the grid, the formula bar, the selection, the cursor. But there is no data layer. No variables hold cell values. No formula parser. No evaluation engine. When you type =A1+1 and press Enter, the LLM predicts what a spreadsheet should show next. It returns 11 — not because it computed it, but because it has seen enough spreadsheets to know what happens. The contract is honored. The mechanism is absent.`

const FULL_EXPLANATION = `There is no building at all. Not even a front door. The entire UI — every pixel, every cell border, every formula bar — is generated by the LLM as pure static HTML. When you click, the browser takes a screenshot, marks where you clicked with a red crosshair, and sends it alongside the raw DOM event. The LLM looks at the image, interprets your action, and returns the next frame. No code runs the spreadsheet. No state machine tracks your edits. Just a model mapping (history + action) → next observation, frame by frame.`

type Tab = 'hybrid' | 'full'

export function App() {
  const [tab, setTab] = useState<Tab>('hybrid')
  const [apiKey, setApiKey] = useState(() => sessionStorage.getItem('anthropic_api_key') ?? '')
  const [hybridLogs, setHybridLogs] = useState<LogEntry[]>([])
  const [fullLogs, setFullLogs] = useState<LogEntry[]>([])

  const client = useMemo<Anthropic | null>(
    () => apiKey ? createClient(apiKey) : null,
    [apiKey],
  )

  const handleApiKeyChange = useCallback((value: string) => {
    setApiKey(value)
    sessionStorage.setItem('anthropic_api_key', value)
  }, [])

  const addHybridLog = useCallback((entry: LogEntry) => {
    setHybridLogs((prev) => [...prev, entry])
  }, [])

  const addFullLog = useCallback((entry: LogEntry) => {
    setFullLogs((prev) => [...prev, entry])
  }, [])

  const tabs: { id: Tab; label: string }[] = [
    { id: 'hybrid', label: 'Hybrid' },
    { id: 'full', label: 'Full' },
  ]

  const explanations: Record<Tab, string> = {
    hybrid: HYBRID_EXPLANATION,
    full: FULL_EXPLANATION,
  }

  const logs: Record<Tab, LogEntry[]> = {
    hybrid: hybridLogs,
    full: fullLogs,
  }

  return (
    <div className="flex flex-col h-screen select-none"
      style={{ fontFamily: "'Aptos', 'Calibri', 'Segoe UI', system-ui, sans-serif" }}>

      {/* Title bar */}
      <div className="h-8 flex items-center px-3 gap-2 shrink-0"
        style={{
          background: 'linear-gradient(180deg, #1e3a2a 0%, #162e22 100%)',
          boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
        }}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="opacity-90">
          <rect x="1" y="1" width="14" height="14" rx="2" fill="#fff" fillOpacity="0.1" stroke="#fff" strokeOpacity="0.3" strokeWidth="0.5"/>
          <path d="M4 4h3v3H4zM9 4h3v3H9zM4 9h3v3H4zM9 9h3v3H9z" fill="#fff" fillOpacity="0.5"/>
        </svg>
        <span className="text-white/80 text-[11px] font-medium tracking-wide">
          Excellusion
        </span>
        <div className="ml-auto flex items-center gap-1.5">
          <label className="text-white/40 text-[10px]" htmlFor="api-key">Anthropic API Key</label>
          <div className="relative group">
            <div className="flex items-center justify-center cursor-help" style={{
              width: 14, height: 14, borderRadius: '50%',
              border: '1px solid rgba(255,255,255,0.25)',
              fontSize: 9, color: 'rgba(255,255,255,0.4)',
            }}>?</div>
            <div className="absolute right-0 top-5 hidden group-hover:block" style={{ zIndex: 100 }}>
              <div style={{
                background: '#333', border: '1px solid #444', borderRadius: 6,
                padding: '8px 12px', width: 220, fontSize: 10, lineHeight: '1.5',
                color: '#ccc', boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
              }}>
                Your API key is stored in sessionStorage and never sent to any server. It will be lost when you close this tab. All LLM requests go directly from your browser to the Anthropic API.
              </div>
            </div>
          </div>
          <input
            id="api-key"
            type="password"
            placeholder="sk-ant-..."
            value={apiKey}
            onChange={(e) => handleApiKeyChange(e.target.value)}
            className="text-[10px] px-1.5 py-0.5 rounded"
            style={{
              width: 180,
              background: 'rgba(255,255,255,0.08)',
              border: '1px solid rgba(255,255,255,0.15)',
              color: 'rgba(255,255,255,0.8)',
              outline: 'none',
            }}
          />
        </div>
      </div>

      {/* Mode tabs */}
      <div className="flex items-end px-2 gap-0 shrink-0 border-b"
        style={{
          background: '#252525',
          borderColor: '#333',
        }}>
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className="pb-1.5 pt-1.5 px-4 text-[11px] border-b-2 transition-colors cursor-pointer"
            style={{
              color: tab === t.id ? '#4ec9b0' : '#888',
              borderColor: tab === t.id ? '#4ec9b0' : 'transparent',
              fontWeight: tab === t.id ? 600 : 400,
            }}>
            {t.label}
          </button>
        ))}
      </div>

      {/* Explanation panel */}
      <div className="shrink-0 px-4 py-3 border-b select-text"
        style={{
          background: '#1e1e1e',
          borderColor: '#333',
          fontSize: 12,
          lineHeight: '1.5',
          color: '#ddd',
        }}>
        {explanations[tab]}
      </div>

      {/* Sheet + Log pane */}
      <div className="flex flex-1 overflow-hidden" style={{ background: '#1a1a1a' }}>
        <div className="flex-1 flex flex-col overflow-hidden">
          {!client ? (
            <div className="flex-1 flex items-center justify-center text-[13px]" style={{ color: '#555' }}>
              Enter your Anthropic API key above to start.
            </div>
          ) : (
            <>
              {tab === 'hybrid' && <HybridSheet client={client} onLog={addHybridLog} />}
              {tab === 'full' && <FullSheet client={client} onLog={addFullLog} />}
            </>
          )}
        </div>
        <div style={{ width: 360, borderLeft: '1px solid #2a2a2a' }} className="shrink-0">
          <LogPane entries={logs[tab]} mode={tab === 'hybrid' ? 'hybrid' : 'full'} />
        </div>
      </div>

      {/* Status bar */}
      <div className="flex items-center shrink-0 px-3"
        style={{
          background: '#1e3a2a',
          height: 22,
          fontSize: 10,
          color: 'rgba(255,255,255,0.4)',
        }}>
        <span>Ready</span>
      </div>
    </div>
  )
}
