import { useState, useCallback, useMemo, useEffect } from 'react'
import { HybridSheet } from '~/components/HybridSheet'
import { FullSheet } from '~/components/FullSheet'
import { LogPane } from '~/components/LogPane'
import type { LogEntry } from '~/components/LogPane'
import {
  createClient,
  prewarmCache,
  HYBRID_SYSTEM,
  FULL_SYSTEM,
  DEFAULT_MODEL_ID,
  KEY_LABEL,
  KEY_PLACEHOLDER,
  KEY_STORAGE,
  MODEL_GROUPS,
  getModel,
} from '~/lib/llm'
import type { LlmClient, ModelChoiceId, ProviderId } from '~/lib/llm'

const HYBRID_EXPLANATION = `The building has a front door, but nothing behind it. This spreadsheet UI is coded in React — the grid, the formula bar, the selection, the cursor. But there is no data layer. No variables hold cell values. No formula parser. No evaluation engine. When you type =A1+1 and press Enter, the LLM predicts what a spreadsheet should show next. It returns 11 — not because it computed it, but because it has seen enough spreadsheets to know what happens. The contract is honored. The mechanism is absent.`

const FULL_EXPLANATION = `There is no building at all. Not even a front door. The entire UI — every pixel, every cell border, every formula bar — is generated by the LLM as pure static HTML. When you click, the browser takes a screenshot, marks where you clicked with a red crosshair, and sends it alongside the raw DOM event. The LLM looks at the image, interprets your action, and returns the next frame. No code runs the spreadsheet. No state machine tracks your edits. Just a model mapping (history + action) → next observation, frame by frame.`

type Tab = 'hybrid' | 'full'

function readModel(): ModelChoiceId {
  return DEFAULT_MODEL_ID
}

function emptyKeys(): Record<ProviderId, string> {
  return {
    anthropic: sessionStorage.getItem(KEY_STORAGE.anthropic) ?? '',
    openai: sessionStorage.getItem(KEY_STORAGE.openai) ?? '',
    openrouter: sessionStorage.getItem(KEY_STORAGE.openrouter) ?? '',
    chatjimmy: '',
  }
}

export function App() {
  const [tab, setTab] = useState<Tab>('hybrid')
  const [modelId, setModelId] = useState<ModelChoiceId>(readModel)
  const [keys, setKeys] = useState<Record<ProviderId, string>>(emptyKeys)
  const [hybridLogs, setHybridLogs] = useState<LogEntry[]>([])
  const [fullLogs, setFullLogs] = useState<LogEntry[]>([])

  const spec = getModel(modelId)
  const provider = spec.provider
  const needsKey = provider !== 'chatjimmy'
  const apiKey = keys[provider] ?? ''

  const client = useMemo<LlmClient | null>(() => {
    if (!needsKey) return createClient(modelId, '')
    return apiKey ? createClient(modelId, apiKey) : null
  }, [modelId, apiKey, needsKey])

  useEffect(() => {
    if (!client) return
    let cancelled = false
    Promise.all([
      prewarmCache(client, HYBRID_SYSTEM),
      prewarmCache(client, FULL_SYSTEM),
    ]).catch((err) => {
      if (!cancelled) console.warn('cache prewarm failed', err)
    })
    return () => { cancelled = true }
  }, [client])

  const handleModelChange = useCallback((next: ModelChoiceId) => {
    setModelId(next)
    setHybridLogs([])
    setFullLogs([])
  }, [])

  const handleApiKeyChange = useCallback((value: string) => {
    setKeys((prev) => ({ ...prev, [provider]: value }))
    sessionStorage.setItem(KEY_STORAGE[provider], value)
  }, [provider])

  const addHybridLog = useCallback((entry: LogEntry) => {
    setHybridLogs((prev) => [...prev, entry])
  }, [])

  const addFullLog = useCallback((entry: LogEntry) => {
    setFullLogs((prev) => [...prev, entry])
  }, [])

  const tabs: { id: Tab; label: string }[] = [
    { id: 'hybrid', label: 'Hybrid' },
    { id: 'full', label: 'Full' },
  ]

  const explanations: Record<Tab, string> = {
    hybrid: HYBRID_EXPLANATION,
    full: FULL_EXPLANATION,
  }

  const logs: Record<Tab, LogEntry[]> = {
    hybrid: hybridLogs,
    full: fullLogs,
  }

  const keyPlaceholder = KEY_PLACEHOLDER[provider]
  const keyLabel = KEY_LABEL[provider]
  const emptyHint = needsKey ? `Enter your ${keyLabel} above to start.` : 'ChatJimmy is ready.'

  return (
    <div className="flex flex-col h-screen select-none"
      style={{ fontFamily: "'Aptos', 'Calibri', 'Segoe UI', system-ui, sans-serif" }}>

      <div className="h-8 flex items-center px-3 gap-2 shrink-0"
        style={{
          background: 'linear-gradient(180deg, #1e3a2a 0%, #162e22 100%)',
          boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
        }}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" className="opacity-90">
          <rect x="1" y="1" width="14" height="14" rx="2" fill="#fff" fillOpacity="0.1" stroke="#fff" strokeOpacity="0.3" strokeWidth="0.5"/>
          <path d="M4 4h3v3H4zM9 4h3v3H9zM4 9h3v3H4zM9 9h3v3H9z" fill="#fff" fillOpacity="0.5"/>
        </svg>
        <span className="text-white/80 text-[11px] font-medium tracking-wide">
          Excellusion
        </span>
        <a
          href="https://lufzle.dev/write/nobody-wrote-the-matrix/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-white/45 hover:text-white/80 text-[10px] underline underline-offset-2"
        >
          Read the essay
        </a>
        <div className="ml-auto flex items-center gap-1.5">
          <select
            aria-label="Model"
            value={modelId}
            onChange={(e) => handleModelChange(e.target.value as ModelChoiceId)}
            className="text-[10px] px-1 py-0.5 rounded cursor-pointer"
            style={{
              background: 'rgba(255,255,255,0.08)',
              border: '1px solid rgba(255,255,255,0.15)',
              color: 'rgba(255,255,255,0.8)',
              outline: 'none',
              maxWidth: 190,
            }}
          >
            {MODEL_GROUPS.map((group) => (
              <optgroup key={group.group} label={group.group}>
                {group.models.map((m) => (
                  <option key={m.id} value={m.id} style={{ color: '#111' }}>{m.label}</option>
                ))}
              </optgroup>
            ))}
          </select>
          {needsKey ? (
            <>
              <label className="text-white/40 text-[10px]" htmlFor="api-key">{keyLabel}</label>
              <div className="relative group">
                <div className="flex items-center justify-center cursor-help" style={{
                  width: 14, height: 14, borderRadius: '50%',
                  border: '1px solid rgba(255,255,255,0.25)',
                  fontSize: 9, color: 'rgba(255,255,255,0.4)',
                }}>?</div>
                <div className="absolute right-0 top-5 hidden group-hover:block" style={{ zIndex: 100 }}>
                  <div style={{
                    background: '#333', border: '1px solid #444', borderRadius: 6,
                    padding: '8px 12px', width: 240, fontSize: 10, lineHeight: '1.5',
                    color: '#ccc', boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
                  }}>
                    Your API key is stored in sessionStorage and never sent to any server. It will be lost when you close this tab. Requests go from your browser to {spec.group} ({spec.apiModel}). Test keys in .env are not used here.
                  </div>
                </div>
              </div>
              <input
                id="api-key"
                type="password"
                placeholder={keyPlaceholder}
                value={apiKey}
                onChange={(e) => handleApiKeyChange(e.target.value)}
                className="text-[10px] px-1.5 py-0.5 rounded"
                style={{
                  width: 180,
                  background: 'rgba(255,255,255,0.08)',
                  border: '1px solid rgba(255,255,255,0.15)',
                  color: 'rgba(255,255,255,0.8)',
                  outline: 'none',
                }}
              />
            </>
          ) : (
            <span className="text-white/40 text-[10px]">
              No API key · llama3.1-8B via{' '}
              <a
                href="https://chatjimmy.ai/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-white/70 hover:text-white underline underline-offset-2"
              >
                chatjimmy.ai
              </a>
            </span>
          )}
        </div>
      </div>

      <div className="flex items-end px-2 gap-0 shrink-0 border-b"
        style={{
          background: '#252525',
          borderColor: '#333',
        }}>
        {tabs.map((t) => {
          const fullBlocked = t.id === 'full' && provider === 'chatjimmy'
          const active = tab === t.id
          return (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className="pb-1.5 pt-1.5 px-4 text-[11px] border-b-2 transition-colors cursor-pointer"
              style={{
                color: fullBlocked ? '#555' : active ? '#4ec9b0' : '#888',
                borderColor: active ? (fullBlocked ? '#555' : '#4ec9b0') : 'transparent',
                fontWeight: active ? 600 : 400,
              }}>
              {t.label}
            </button>
          )
        })}
      </div>

      <div className="shrink-0 px-4 py-3 border-b select-text"
        style={{
          background: '#1e1e1e',
          borderColor: '#333',
          fontSize: 12,
          lineHeight: '1.5',
          color: '#ddd',
        }}>
        {explanations[tab]}
      </div>

      <div className="flex flex-1 overflow-hidden" style={{ background: '#1a1a1a' }}>
        <div className="flex-1 flex flex-col overflow-hidden">
          {!client ? (
            <div className="flex-1 flex items-center justify-center text-[13px]" style={{ color: '#555' }}>
              {emptyHint}
            </div>
          ) : tab === 'full' && provider === 'chatjimmy' ? (
            <div className="flex-1 flex items-center justify-center text-[13px]" style={{ color: '#888' }}>
              Too complex for this model
            </div>
          ) : (
            <>
              {tab === 'hybrid' && <HybridSheet key={`hybrid-${modelId}`} client={client} onLog={addHybridLog} />}
              {tab === 'full' && <FullSheet key={`full-${modelId}`} client={client} onLog={addFullLog} />}
            </>
          )}
        </div>
        <div style={{ width: 360, borderLeft: '1px solid #2a2a2a' }} className="shrink-0">
          <LogPane entries={logs[tab]} mode={tab === 'hybrid' ? 'hybrid' : 'full'} spec={spec} />
        </div>
      </div>

      <div className="flex items-center shrink-0 px-3"
        style={{
          background: '#1e3a2a',
          height: 22,
          fontSize: 10,
          color: 'rgba(255,255,255,0.4)',
        }}>
        <span>Ready · {spec.label} · effort {spec.effort}</span>
      </div>
    </div>
  )
}
